//! Parity with the official PaddleOCR pipeline.
//!
//! `tests/reference/*.json` hold PaddleOCR 3.x outputs for the same ONNX
//! models and images (generated by `scripts/paddleocr_reference.py` with
//! ONNX Runtime, document preprocessing and text-line orientation off). This
//! test runs our engine with PaddleOCR's default detection settings and
//! compares:
//!
//! * detection: boxes are matched greedily by IoU (>= 0.5) of their
//!   axis-aligned bounds; precision / recall / F1 are computed over regions;
//! * recognition: for matched pairs, the share of identical strings and the
//!   mean character similarity (1 - normalised edit distance).
//!
//! Models missing from the fixtures are skipped. Run with `--nocapture` to
//! print the per-model report.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use pure_onnx_ocr::{min_area_quad, DetLimitType, OcrEngineBuilder};

const IOU_THRESHOLD: f64 = 0.5;

fn fixture_dir() -> PathBuf {
    std::env::var_os("PURE_ONNX_OCR_FIXTURE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures"))
}

fn model_dirs(model: &str) -> Option<(PathBuf, PathBuf)> {
    let (det, rec) = match model {
        "v6-tiny" => ("ppocrv6/tiny_det", "ppocrv6/tiny_rec"),
        "v6-small" => ("ppocrv6/small_det", "ppocrv6/small_rec"),
        "v6-medium" => ("ppocrv6/medium_det", "ppocrv6/medium_rec"),
        "v5-mobile" => ("ppocrv5/mobile_det", "ppocrv5/mobile_rec"),
        _ => return None,
    };
    let models = fixture_dir().join("models");
    let (det, rec) = (models.join(det), models.join(rec));
    (det.join("inference.onnx").exists() && rec.join("inference.onnx").exists())
        .then_some((det, rec))
}

#[derive(Debug, Clone)]
struct Region {
    text: String,
    bounds: [f64; 4], // min_x, min_y, max_x, max_y
}

fn bounds_of(points: impl Iterator<Item = (f64, f64)>) -> [f64; 4] {
    points.fold(
        [
            f64::INFINITY,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::NEG_INFINITY,
        ],
        |[x0, y0, x1, y1], (x, y)| [x0.min(x), y0.min(y), x1.max(x), y1.max(y)],
    )
}

fn iou(a: &[f64; 4], b: &[f64; 4]) -> f64 {
    let w = (a[2].min(b[2]) - a[0].max(b[0])).max(0.0);
    let h = (a[3].min(b[3]) - a[1].max(b[1])).max(0.0);
    let inter = w * h;
    let area = |r: &[f64; 4]| (r[2] - r[0]).max(0.0) * (r[3] - r[1]).max(0.0);
    let union = area(a) + area(b) - inter;
    if union <= 0.0 {
        0.0
    } else {
        inter / union
    }
}

fn levenshtein(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let mut prev: Vec<usize> = (0..=b.len()).collect();
    for (i, ca) in a.iter().enumerate() {
        let mut cur = vec![i + 1; b.len() + 1];
        for (j, cb) in b.iter().enumerate() {
            let cost = usize::from(ca != cb);
            cur[j + 1] = (prev[j] + cost).min(prev[j + 1] + 1).min(cur[j] + 1);
        }
        prev = cur;
    }
    prev[b.len()]
}

fn similarity(a: &str, b: &str) -> f64 {
    let len = a.chars().count().max(b.chars().count());
    if len == 0 {
        1.0
    } else {
        1.0 - levenshtein(a, b) as f64 / len as f64
    }
}

#[derive(Debug, Default)]
struct Report {
    reference: usize,
    ours: usize,
    matched: usize,
    exact: usize,
    similarity_sum: f64,
    mismatches: Vec<(String, String)>,
}

impl Report {
    fn precision(&self) -> f64 {
        self.matched as f64 / self.ours.max(1) as f64
    }
    fn recall(&self) -> f64 {
        self.matched as f64 / self.reference.max(1) as f64
    }
    fn f1(&self) -> f64 {
        let (p, r) = (self.precision(), self.recall());
        if p + r == 0.0 {
            0.0
        } else {
            2.0 * p * r / (p + r)
        }
    }
    fn exact_rate(&self) -> f64 {
        self.exact as f64 / self.matched.max(1) as f64
    }
    fn mean_similarity(&self) -> f64 {
        self.similarity_sum / self.matched.max(1) as f64
    }
}

fn compare(reference: &[Region], ours: &[Region]) -> Report {
    let mut pairs: Vec<(f64, usize, usize)> = Vec::new();
    for (i, r) in reference.iter().enumerate() {
        for (j, o) in ours.iter().enumerate() {
            let value = iou(&r.bounds, &o.bounds);
            if value >= IOU_THRESHOLD {
                pairs.push((value, i, j));
            }
        }
    }
    pairs.sort_by(|a, b| b.0.total_cmp(&a.0));
    let (mut used_ref, mut used_ours) = (vec![false; reference.len()], vec![false; ours.len()]);
    let mut report = Report {
        reference: reference.len(),
        ours: ours.len(),
        ..Report::default()
    };
    for (_, i, j) in pairs {
        if used_ref[i] || used_ours[j] {
            continue;
        }
        used_ref[i] = true;
        used_ours[j] = true;
        report.matched += 1;
        let (expected, actual) = (&reference[i].text, &ours[j].text);
        if expected == actual {
            report.exact += 1;
        } else {
            report.mismatches.push((expected.clone(), actual.clone()));
        }
        report.similarity_sum += similarity(expected, actual);
    }
    report
}

fn load_reference(path: &Path) -> (String, String, Vec<Region>) {
    let json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    let regions = json["regions"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| Region {
            text: r["text"].as_str().unwrap().to_string(),
            bounds: bounds_of(
                r["quad"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|p| (p[0].as_f64().unwrap(), p[1].as_f64().unwrap())),
            ),
        })
        .collect();
    (
        json["model"].as_str().unwrap().to_string(),
        json["image"].as_str().unwrap().to_string(),
        regions,
    )
}

/// Runs every available (model, image) pair and returns the reports.
fn run_all() -> Vec<(String, String, Report)> {
    let reference_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/reference");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&reference_dir)
        .map(|entries| entries.filter_map(|e| e.ok().map(|e| e.path())).collect())
        .unwrap_or_default();
    files.retain(|p| p.extension().is_some_and(|e| e == "json"));
    files.sort();

    let mut engines = HashMap::new();
    let mut reports = Vec::new();
    for file in files {
        let (model, image, reference) = load_reference(&file);
        let Some((det, rec)) = model_dirs(&model) else {
            eprintln!("skipping {model}: models not in fixtures");
            continue;
        };
        let image_path = fixture_dir().join("images").join(&image);
        if !image_path.exists() {
            eprintln!("skipping {image}: not in fixtures");
            continue;
        }
        let engine = engines.entry(model.clone()).or_insert_with(|| {
            // PaddleOCR 3.x pipeline defaults.
            OcrEngineBuilder::new()
                .det_model_dir(&det)
                .rec_model_dir(&rec)
                .det_limit_type(DetLimitType::Min)
                .det_limit_side_len(64)
                .det_max_side_limit(4000)
                .build()
                .unwrap()
        });
        let ours: Vec<Region> = engine
            .run_from_path(&image_path)
            .unwrap()
            .into_iter()
            .map(|r| {
                let quad = min_area_quad(&r.bounding_box).unwrap();
                Region {
                    text: r.text,
                    bounds: bounds_of(quad.into_iter()),
                }
            })
            .collect();
        reports.push((model, image, compare(&reference, &ours)));
    }
    reports
}

#[test]
fn matches_paddleocr_reference_outputs() {
    let reports = run_all();
    if reports.is_empty() {
        eprintln!("no reference/model pairs available; skipping");
        return;
    }
    eprintln!("| model | image | paddle | ours | matched | det P | det R | det F1 | text exact | char sim |");
    eprintln!("| :--- | :--- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");
    for (model, image, r) in &reports {
        eprintln!(
            "| {model} | {image} | {} | {} | {} | {:.3} | {:.3} | {:.3} | {:.3} | {:.3} |",
            r.reference,
            r.ours,
            r.matched,
            r.precision(),
            r.recall(),
            r.f1(),
            r.exact_rate(),
            r.mean_similarity()
        );
    }
    for (model, image, r) in &reports {
        for (expected, actual) in &r.mismatches {
            eprintln!("  {model}/{image}: paddle {expected:?} vs ours {actual:?}");
        }
    }
    for (model, image, r) in &reports {
        let text_checked = !TEXT_EXEMPT.contains(&(model.as_str(), image.as_str()));
        assert!(
            r.f1() >= MIN_DET_F1
                && (!text_checked || r.mean_similarity() >= MIN_CHAR_SIMILARITY),
            "{model}/{image}: det F1 {:.3} (min {MIN_DET_F1}), char similarity {:.3} (min {MIN_CHAR_SIMILARITY})",
            r.f1(),
            r.mean_similarity()
        );
    }
}

// Thresholds are set from the measured parity (see docs/devlog/ppocrv6/
// task-v6-010-paddle-parity.md) with some margin: detection F1 was
// 0.95-1.00 and character similarity 0.95-1.00 for every model that can
// read the image's script.
const MIN_DET_F1: f64 = 0.90;
const MIN_CHAR_SIMILARITY: f64 = 0.93;

/// (model, image) pairs whose text is not compared: PP-OCRv6 tiny has no
/// hiragana / katakana in its dictionary, so both implementations output
/// look-alike kanji for Japanese and the strings are not meaningful.
const TEXT_EXEMPT: &[(&str, &str)] = &[("v6-tiny", "ja.jpg")];

#[test]
fn levenshtein_and_iou_helpers() {
    assert_eq!(levenshtein("kitten", "sitting"), 3);
    assert_eq!(levenshtein("", "abc"), 3);
    assert!((similarity("登机牌", "登机牌") - 1.0).abs() < 1e-12);
    assert!((iou(&[0.0, 0.0, 2.0, 2.0], &[1.0, 0.0, 3.0, 2.0]) - 1.0 / 3.0).abs() < 1e-12);
}
