//! Reader for the `inference.yml` files shipped next to PaddleOCR 3.x model
//! exports (PP-OCRv5, PP-OCRv6, ...).
//!
//! The files are generated by PyYAML in block style. Only the subset of YAML
//! emitted by PyYAML for these configs is supported: block mappings, block
//! sequences (including the "indentless" form where `- item` sits at the same
//! indentation as its parent key), nested `- - x` sequences, plain scalars,
//! single/double quoted scalars, and anchors/aliases (aliases are kept as
//! opaque scalars). Flow collections and multi-line scalars are not needed by
//! the OCR configs and are rejected with a descriptive error.
//!
//! No YAML dependency is pulled in so the crate stays pure Rust with a small
//! dependency tree.

use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Channel order expected by the model input tensor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorOrder {
    /// Red, green, blue (the order produced by the `image` crate).
    Rgb,
    /// Blue, green, red (the OpenCV order PaddleOCR models are trained with).
    Bgr,
}

impl ColorOrder {
    /// Returns the source RGB channel index used for output channel `channel`.
    pub fn source_channel(self, channel: usize) -> usize {
        match self {
            ColorOrder::Rgb => channel,
            ColorOrder::Bgr => 2 - channel,
        }
    }
}

/// Values extracted from a PaddleOCR `inference.yml`.
///
/// Every field is optional because detection and recognition configs carry
/// different sections.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PaddleInferenceConfig {
    /// `Global.model_name`, e.g. `PP-OCRv6_small_rec`.
    pub model_name: Option<String>,
    /// `DecodeImage.img_mode` converted to a channel order.
    pub color_order: Option<ColorOrder>,
    /// `NormalizeImage.mean` (detection only).
    pub normalize_mean: Option<[f32; 3]>,
    /// `NormalizeImage.std` (detection only).
    pub normalize_std: Option<[f32; 3]>,
    /// `RecResizeImg.image_shape` as `[channels, height, width]`.
    pub rec_image_shape: Option<[u32; 3]>,
    /// `PostProcess.name`, e.g. `DBPostProcess` or `CTCLabelDecode`.
    pub post_process_name: Option<String>,
    /// `PostProcess.thresh` (DBNet binarisation threshold).
    pub det_thresh: Option<f32>,
    /// `PostProcess.box_thresh` (DBNet box score threshold).
    pub det_box_thresh: Option<f32>,
    /// `PostProcess.unclip_ratio`.
    pub det_unclip_ratio: Option<f32>,
    /// `PostProcess.max_candidates`.
    pub det_max_candidates: Option<usize>,
    /// `PostProcess.character_dict` (recognition only).
    pub character_dict: Option<Vec<String>>,
    /// `ResizeImage.size` as `[width, height]` (classification models).
    pub cls_resize_size: Option<[u32; 2]>,
    /// `ResizeImage.resize_short` (classification models).
    pub cls_resize_short: Option<u32>,
    /// `CropImage.size`, a centre crop applied after resizing.
    pub cls_crop_size: Option<u32>,
    /// `PostProcess.Topk.label_list` (classification models).
    pub label_list: Option<Vec<String>>,
}

/// Errors produced while reading an `inference.yml` file.
#[derive(Debug)]
pub enum PaddleConfigError {
    /// The file could not be read.
    Io { source: io::Error, path: PathBuf },
    /// The file uses YAML syntax outside the supported subset.
    Syntax { line: usize, message: String },
    /// A known key held a value of an unexpected shape.
    InvalidValue { key: &'static str, message: String },
}

impl fmt::Display for PaddleConfigError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PaddleConfigError::Io { source, path } => {
                write!(f, "failed to read inference config {:?}: {}", path, source)
            }
            PaddleConfigError::Syntax { line, message } => {
                write!(f, "unsupported YAML on line {}: {}", line, message)
            }
            PaddleConfigError::InvalidValue { key, message } => {
                write!(f, "invalid value for `{}`: {}", key, message)
            }
        }
    }
}

impl std::error::Error for PaddleConfigError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            PaddleConfigError::Io { source, .. } => Some(source),
            _ => None,
        }
    }
}

impl PaddleInferenceConfig {
    /// Reads and interprets an `inference.yml` file.
    pub fn from_path(path: impl AsRef<Path>) -> Result<Self, PaddleConfigError> {
        let path = path.as_ref();
        let text = fs::read_to_string(path).map_err(|source| PaddleConfigError::Io {
            source,
            path: path.to_path_buf(),
        })?;
        Self::from_yaml_str(&text)
    }

    /// Interprets the contents of an `inference.yml` file.
    pub fn from_yaml_str(text: &str) -> Result<Self, PaddleConfigError> {
        let root = parse_yaml(text)?;
        let mut config = PaddleInferenceConfig {
            model_name: root
                .get("Global")
                .and_then(|g| g.get("model_name"))
                .and_then(Yaml::as_str)
                .map(str::to_string),
            ..PaddleInferenceConfig::default()
        };

        if let Some(ops) = root
            .get("PreProcess")
            .and_then(|p| p.get("transform_ops"))
            .and_then(Yaml::as_seq)
        {
            for op in ops {
                if let Some(decode) = op.get("DecodeImage") {
                    if let Some(mode) = decode.get("img_mode").and_then(Yaml::as_str) {
                        config.color_order = Some(parse_color_order(mode)?);
                    }
                }
                if let Some(normalize) = op.get("NormalizeImage") {
                    if let Some(mean) = normalize.get("mean") {
                        config.normalize_mean = Some(float_triplet("NormalizeImage.mean", mean)?);
                    }
                    if let Some(std) = normalize.get("std") {
                        config.normalize_std = Some(float_triplet("NormalizeImage.std", std)?);
                    }
                }
                if let Some(resize) = op.get("ResizeImage") {
                    if let Some(size) = resize.get("size") {
                        let items = scalar_list("ResizeImage.size", size)?;
                        if items.len() != 2 {
                            return Err(PaddleConfigError::InvalidValue {
                                key: "ResizeImage.size",
                                message: format!("expected 2 entries, found {}", items.len()),
                            });
                        }
                        config.cls_resize_size = Some([
                            parse_u32("ResizeImage.size", items[0])?,
                            parse_u32("ResizeImage.size", items[1])?,
                        ]);
                    }
                    if let Some(short) = resize.get("resize_short").and_then(Yaml::as_str) {
                        config.cls_resize_short =
                            Some(parse_u32("ResizeImage.resize_short", short)?);
                    }
                }
                if let Some(crop) = op.get("CropImage") {
                    if let Some(size) = crop.get("size").and_then(Yaml::as_str) {
                        config.cls_crop_size = Some(parse_u32("CropImage.size", size)?);
                    }
                }
                if let Some(resize) = op.get("RecResizeImg") {
                    if let Some(shape) = resize.get("image_shape") {
                        config.rec_image_shape =
                            Some(uint_triplet("RecResizeImg.image_shape", shape)?);
                    }
                }
            }
        }

        if let Some(post) = root.get("PostProcess") {
            config.post_process_name = post.get("name").and_then(Yaml::as_str).map(str::to_string);
            config.det_thresh = optional_f32(post, "thresh", "PostProcess.thresh")?;
            config.det_box_thresh = optional_f32(post, "box_thresh", "PostProcess.box_thresh")?;
            config.det_unclip_ratio =
                optional_f32(post, "unclip_ratio", "PostProcess.unclip_ratio")?;
            config.det_max_candidates = match post.get("max_candidates").and_then(Yaml::as_str) {
                Some(raw) => {
                    Some(
                        raw.parse::<usize>()
                            .map_err(|_| PaddleConfigError::InvalidValue {
                                key: "PostProcess.max_candidates",
                                message: format!("`{}` is not an unsigned integer", raw),
                            })?,
                    )
                }
                None => None,
            };
            if let Some(labels) = post.get("Topk").and_then(|t| t.get("label_list")) {
                let labels = scalar_list("PostProcess.Topk.label_list", labels)?;
                config.label_list = Some(labels.into_iter().map(str::to_string).collect());
            }
            if let Some(dict) = post.get("character_dict") {
                let items = dict
                    .as_seq()
                    .ok_or_else(|| PaddleConfigError::InvalidValue {
                        key: "PostProcess.character_dict",
                        message: "expected a sequence of characters".to_string(),
                    })?;
                let mut tokens = Vec::with_capacity(items.len());
                for item in items {
                    let token = item
                        .as_str()
                        .ok_or_else(|| PaddleConfigError::InvalidValue {
                            key: "PostProcess.character_dict",
                            message: "expected every entry to be a scalar".to_string(),
                        })?;
                    tokens.push(token.to_string());
                }
                config.character_dict = Some(tokens);
            }
        }

        Ok(config)
    }
}

fn parse_color_order(mode: &str) -> Result<ColorOrder, PaddleConfigError> {
    match mode.to_ascii_uppercase().as_str() {
        "BGR" => Ok(ColorOrder::Bgr),
        "RGB" => Ok(ColorOrder::Rgb),
        other => Err(PaddleConfigError::InvalidValue {
            key: "DecodeImage.img_mode",
            message: format!("unsupported image mode `{}`", other),
        }),
    }
}

fn optional_f32(
    node: &Yaml,
    key: &str,
    label: &'static str,
) -> Result<Option<f32>, PaddleConfigError> {
    match node.get(key).and_then(Yaml::as_str) {
        Some(raw) => parse_number(raw).map(|v| Some(v as f32)).ok_or_else(|| {
            PaddleConfigError::InvalidValue {
                key: label,
                message: format!("`{}` is not a number", raw),
            }
        }),
        None => Ok(None),
    }
}

/// Parses YAML numbers, including PaddleOCR's `1./255.` style expressions.
fn parse_number(raw: &str) -> Option<f64> {
    if let Some((num, den)) = raw.split_once('/') {
        let num = parse_number(num.trim())?;
        let den = parse_number(den.trim())?;
        if den == 0.0 {
            return None;
        }
        return Some(num / den);
    }
    raw.trim().parse::<f64>().ok()
}

fn parse_u32(key: &'static str, raw: &str) -> Result<u32, PaddleConfigError> {
    raw.parse::<u32>()
        .map_err(|_| PaddleConfigError::InvalidValue {
            key,
            message: format!("`{}` is not an unsigned integer", raw),
        })
}

fn scalar_list<'a>(key: &'static str, node: &'a Yaml) -> Result<Vec<&'a str>, PaddleConfigError> {
    let items = node
        .as_seq()
        .ok_or_else(|| PaddleConfigError::InvalidValue {
            key,
            message: "expected a sequence".to_string(),
        })?;
    items
        .iter()
        .map(|item| {
            item.as_str()
                .ok_or_else(|| PaddleConfigError::InvalidValue {
                    key,
                    message: "expected scalar entries".to_string(),
                })
        })
        .collect()
}

fn float_triplet(key: &'static str, node: &Yaml) -> Result<[f32; 3], PaddleConfigError> {
    let values = scalar_triplet(key, node)?;
    let mut out = [0.0f32; 3];
    for (slot, raw) in out.iter_mut().zip(values.iter()) {
        *slot = parse_number(raw).ok_or_else(|| PaddleConfigError::InvalidValue {
            key,
            message: format!("`{}` is not a number", raw),
        })? as f32;
    }
    Ok(out)
}

fn uint_triplet(key: &'static str, node: &Yaml) -> Result<[u32; 3], PaddleConfigError> {
    let values = scalar_triplet(key, node)?;
    let mut out = [0u32; 3];
    for (slot, raw) in out.iter_mut().zip(values.iter()) {
        *slot = raw
            .parse::<u32>()
            .map_err(|_| PaddleConfigError::InvalidValue {
                key,
                message: format!("`{}` is not an unsigned integer", raw),
            })?;
    }
    Ok(out)
}

fn scalar_triplet<'a>(
    key: &'static str,
    node: &'a Yaml,
) -> Result<[&'a str; 3], PaddleConfigError> {
    let items = node
        .as_seq()
        .ok_or_else(|| PaddleConfigError::InvalidValue {
            key,
            message: "expected a sequence".to_string(),
        })?;
    if items.len() != 3 {
        return Err(PaddleConfigError::InvalidValue {
            key,
            message: format!("expected 3 entries, found {}", items.len()),
        });
    }
    let mut out = [""; 3];
    for (slot, item) in out.iter_mut().zip(items.iter()) {
        *slot = item
            .as_str()
            .ok_or_else(|| PaddleConfigError::InvalidValue {
                key,
                message: "expected scalar entries".to_string(),
            })?;
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Minimal block-style YAML parser
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
enum Yaml {
    Null,
    Scalar(String),
    Seq(Vec<Yaml>),
    Map(Vec<(String, Yaml)>),
}

impl Yaml {
    fn get(&self, key: &str) -> Option<&Yaml> {
        match self {
            Yaml::Map(entries) => entries.iter().find(|(k, _)| k == key).map(|(_, v)| v),
            _ => None,
        }
    }

    fn as_str(&self) -> Option<&str> {
        match self {
            Yaml::Scalar(s) => Some(s.as_str()),
            _ => None,
        }
    }

    fn as_seq(&self) -> Option<&[Yaml]> {
        match self {
            Yaml::Seq(items) => Some(items.as_slice()),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
struct Line {
    number: usize,
    indent: usize,
    text: String,
}

fn parse_yaml(text: &str) -> Result<Yaml, PaddleConfigError> {
    let mut lines = Vec::new();
    for (index, raw) in text.split('\n').enumerate() {
        let raw = raw.strip_suffix('\r').unwrap_or(raw);
        let raw = if index == 0 {
            raw.trim_start_matches('\u{FEFF}')
        } else {
            raw
        };
        let indent = raw.len() - raw.trim_start_matches(' ').len();
        let body = &raw[indent..];
        if body.trim_matches(yaml_ws).is_empty() || body.starts_with('#') {
            continue;
        }
        if body == "---" || body == "..." {
            continue;
        }
        if body.starts_with('\t') {
            return Err(PaddleConfigError::Syntax {
                line: index + 1,
                message: "tab indentation is not supported".to_string(),
            });
        }
        lines.push(Line {
            number: index + 1,
            indent,
            text: body.to_string(),
        });
    }

    if lines.is_empty() {
        return Ok(Yaml::Null);
    }

    let mut parser = Parser { lines, pos: 0 };
    let indent = parser.lines[0].indent;
    let value = parser.parse_block(indent)?;
    if parser.pos < parser.lines.len() {
        let line = &parser.lines[parser.pos];
        return Err(PaddleConfigError::Syntax {
            line: line.number,
            message: "unexpected content after document".to_string(),
        });
    }
    Ok(value)
}

fn yaml_ws(c: char) -> bool {
    c == ' ' || c == '\t'
}

struct Parser {
    lines: Vec<Line>,
    pos: usize,
}

impl Parser {
    fn parse_block(&mut self, indent: usize) -> Result<Yaml, PaddleConfigError> {
        let line = &self.lines[self.pos];
        if is_seq_item(&line.text) {
            self.parse_seq(indent)
        } else {
            self.parse_map(indent)
        }
    }

    fn parse_map(&mut self, indent: usize) -> Result<Yaml, PaddleConfigError> {
        let mut entries = Vec::new();
        while self.pos < self.lines.len() {
            let line = self.lines[self.pos].clone();
            if line.indent < indent {
                break;
            }
            if line.indent > indent {
                return Err(PaddleConfigError::Syntax {
                    line: line.number,
                    message: "unexpected indentation".to_string(),
                });
            }
            if is_seq_item(&line.text) {
                break;
            }
            let (key, rest) = split_key(&line.text).ok_or_else(|| PaddleConfigError::Syntax {
                line: line.number,
                message: format!("expected `key: value`, found `{}`", line.text),
            })?;
            let key = decode_scalar(key, line.number)?;
            self.pos += 1;

            let rest = strip_anchor(rest);
            let value = if !rest.is_empty() {
                Yaml::Scalar(decode_scalar(rest, line.number)?)
            } else if let Some(next) = self.lines.get(self.pos) {
                if next.indent > indent {
                    let child_indent = next.indent;
                    self.parse_block(child_indent)?
                } else if next.indent == indent && is_seq_item(&next.text) {
                    // PyYAML's default "indentless" sequence under a mapping key.
                    self.parse_seq(indent)?
                } else {
                    Yaml::Null
                }
            } else {
                Yaml::Null
            };
            entries.push((key, value));
        }
        Ok(Yaml::Map(entries))
    }

    fn parse_seq(&mut self, indent: usize) -> Result<Yaml, PaddleConfigError> {
        let mut items = Vec::new();
        while self.pos < self.lines.len() {
            let line = self.lines[self.pos].clone();
            if line.indent != indent || !is_seq_item(&line.text) {
                if line.indent > indent {
                    return Err(PaddleConfigError::Syntax {
                        line: line.number,
                        message: "unexpected indentation inside sequence".to_string(),
                    });
                }
                break;
            }

            let content = line.text[1..].trim_start_matches(' ');
            let content = strip_anchor(content);
            if content.is_empty() {
                self.pos += 1;
                match self.lines.get(self.pos) {
                    Some(next) if next.indent > indent => {
                        let child_indent = next.indent;
                        items.push(self.parse_block(child_indent)?);
                    }
                    _ => items.push(Yaml::Null),
                }
                continue;
            }

            let nested =
                is_seq_item(content) || (!is_quoted(content) && split_key(content).is_some());
            if nested {
                // Re-interpret the remainder of the line as the first line of a
                // nested block indented to where the content starts.
                let child_indent = line.indent + (line.text.len() - content.len());
                self.lines[self.pos] = Line {
                    number: line.number,
                    indent: child_indent,
                    text: content.to_string(),
                };
                items.push(self.parse_block(child_indent)?);
            } else {
                self.pos += 1;
                items.push(Yaml::Scalar(decode_scalar(content, line.number)?));
            }
        }
        Ok(Yaml::Seq(items))
    }
}

fn is_seq_item(text: &str) -> bool {
    text == "-" || text.starts_with("- ")
}

fn is_quoted(text: &str) -> bool {
    text.starts_with('\'') || text.starts_with('"')
}

/// Splits `key: value` (or `key:`) for plain or quoted keys.
fn split_key(text: &str) -> Option<(&str, &str)> {
    if is_quoted(text) {
        let end = quoted_end(text)?;
        let rest = &text[end..];
        let rest = rest.strip_prefix(':')?;
        if !rest.is_empty() && !rest.starts_with(' ') {
            return None;
        }
        return Some((&text[..end], rest.trim_matches(yaml_ws)));
    }
    if let Some(index) = text.find(": ") {
        return Some((&text[..index], text[index + 2..].trim_matches(yaml_ws)));
    }
    text.strip_suffix(':').map(|key| (key, ""))
}

/// Returns the byte offset just past the closing quote of a quoted scalar.
fn quoted_end(text: &str) -> Option<usize> {
    let quote = text.chars().next()?;
    let mut chars = text.char_indices().skip(1).peekable();
    while let Some((index, c)) = chars.next() {
        if quote == '\'' && c == '\'' {
            if let Some((_, '\'')) = chars.peek() {
                chars.next();
                continue;
            }
            return Some(index + 1);
        }
        if quote == '"' {
            if c == '\\' {
                chars.next();
                continue;
            }
            if c == '"' {
                return Some(index + 1);
            }
        }
    }
    None
}

fn strip_anchor(text: &str) -> &str {
    if let Some(rest) = text.strip_prefix('&') {
        match rest.find(' ') {
            Some(index) => rest[index + 1..].trim_start_matches(' '),
            None => "",
        }
    } else {
        text
    }
}

fn decode_scalar(raw: &str, line: usize) -> Result<String, PaddleConfigError> {
    let raw = raw.trim_matches(yaml_ws);
    if raw.starts_with('\'') {
        let end = quoted_end(raw).ok_or_else(|| PaddleConfigError::Syntax {
            line,
            message: "unterminated single-quoted scalar".to_string(),
        })?;
        if end != raw.len() {
            return Err(PaddleConfigError::Syntax {
                line,
                message: "trailing content after quoted scalar".to_string(),
            });
        }
        return Ok(raw[1..end - 1].replace("''", "'"));
    }
    if raw.starts_with('"') {
        let end = quoted_end(raw).ok_or_else(|| PaddleConfigError::Syntax {
            line,
            message: "unterminated double-quoted scalar".to_string(),
        })?;
        if end != raw.len() {
            return Err(PaddleConfigError::Syntax {
                line,
                message: "trailing content after quoted scalar".to_string(),
            });
        }
        return decode_double_quoted(&raw[1..end - 1], line);
    }
    if raw.starts_with('[') || raw.starts_with('{') {
        return Err(PaddleConfigError::Syntax {
            line,
            message: "flow collections are not supported".to_string(),
        });
    }
    if raw.starts_with('|') || raw.starts_with('>') {
        return Err(PaddleConfigError::Syntax {
            line,
            message: "block scalars are not supported".to_string(),
        });
    }
    Ok(raw.to_string())
}

fn decode_double_quoted(body: &str, line: usize) -> Result<String, PaddleConfigError> {
    let mut out = String::with_capacity(body.len());
    let mut chars = body.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        let escape = chars.next().ok_or_else(|| PaddleConfigError::Syntax {
            line,
            message: "dangling escape in double-quoted scalar".to_string(),
        })?;
        let decoded = match escape {
            '0' => '\0',
            'a' => '\u{07}',
            'b' => '\u{08}',
            't' | '\t' => '\t',
            'n' => '\n',
            'v' => '\u{0B}',
            'f' => '\u{0C}',
            'r' => '\r',
            'e' => '\u{1B}',
            ' ' => ' ',
            '"' => '"',
            '/' => '/',
            '\\' => '\\',
            'N' => '\u{85}',
            '_' => '\u{A0}',
            'L' => '\u{2028}',
            'P' => '\u{2029}',
            'x' => hex_escape(&mut chars, 2, line)?,
            'u' => hex_escape(&mut chars, 4, line)?,
            'U' => hex_escape(&mut chars, 8, line)?,
            other => {
                return Err(PaddleConfigError::Syntax {
                    line,
                    message: format!("unknown escape `\\{}`", other),
                })
            }
        };
        out.push(decoded);
    }
    Ok(out)
}

fn hex_escape(
    chars: &mut std::str::Chars<'_>,
    digits: usize,
    line: usize,
) -> Result<char, PaddleConfigError> {
    let hex: String = chars.by_ref().take(digits).collect();
    let invalid = || PaddleConfigError::Syntax {
        line,
        message: format!("invalid hex escape `{}`", hex),
    };
    if hex.len() != digits {
        return Err(invalid());
    }
    let code = u32::from_str_radix(&hex, 16).map_err(|_| invalid())?;
    char::from_u32(code).ok_or_else(invalid)
}

#[cfg(test)]
mod tests {
    use super::*;

    const DET_YML: &str = "Global:\n  model_name: PP-OCRv6_tiny_det\nHpi:\n  backend_configs:\n    paddle_infer:\n      trt_dynamic_shapes: &id001\n        x:\n        - - 1\n          - 3\n          - 32\n          - 32\n        - - 1\n          - 3\n          - 736\n          - 736\n    tensorrt:\n      dynamic_shapes: *id001\nPostProcess:\n  box_thresh: 0.4\n  max_candidates: 3000\n  name: DBPostProcess\n  thresh: 0.2\n  unclip_ratio: 1.4\nPreProcess:\n  transform_ops:\n  - DecodeImage:\n      channel_first: false\n      img_mode: BGR\n  - DetLabelEncode: null\n  - DetResizeForTest: null\n  - NormalizeImage:\n      mean:\n      - 0.485\n      - 0.456\n      - 0.406\n      order: hwc\n      scale: 1./255.\n      std:\n      - 0.229\n      - 0.224\n      - 0.225\n  - ToCHWImage: null\n";

    #[test]
    fn parses_detection_config() {
        let config = PaddleInferenceConfig::from_yaml_str(DET_YML).unwrap();
        assert_eq!(config.model_name.as_deref(), Some("PP-OCRv6_tiny_det"));
        assert_eq!(config.color_order, Some(ColorOrder::Bgr));
        assert_eq!(config.normalize_mean, Some([0.485, 0.456, 0.406]));
        assert_eq!(config.normalize_std, Some([0.229, 0.224, 0.225]));
        assert_eq!(config.post_process_name.as_deref(), Some("DBPostProcess"));
        assert_eq!(config.det_thresh, Some(0.2));
        assert_eq!(config.det_box_thresh, Some(0.4));
        assert_eq!(config.det_unclip_ratio, Some(1.4));
        assert_eq!(config.det_max_candidates, Some(3000));
        assert!(config.character_dict.is_none());
    }

    #[test]
    fn parses_classifier_config() {
        let yml = "Global:
  model_name: PP-LCNet_x1_0_doc_ori
PreProcess:
  transform_ops:
  - ResizeImage:
      resize_short: 256
  - CropImage:
      size: 224
  - NormalizeImage:
      channel_num: 3
      mean:
      - 0.485
      - 0.456
      - 0.406
      order: ''
      scale: 0.00392156862745098
      std:
      - 0.229
      - 0.224
      - 0.225
  - ToCHWImage: null
PostProcess:
  Topk:
    topk: 1
    label_list:
    - '0'
    - '90'
    - '180'
    - '270'
";
        let config = PaddleInferenceConfig::from_yaml_str(yml).unwrap();
        assert_eq!(config.cls_resize_short, Some(256));
        assert_eq!(config.cls_crop_size, Some(224));
        assert_eq!(config.normalize_mean, Some([0.485, 0.456, 0.406]));
        assert_eq!(
            config.label_list,
            Some(vec!["0".into(), "90".into(), "180".into(), "270".into()])
        );

        let yml = "PreProcess:
  transform_ops:
  - ResizeImage:
      size:
      - 160
      - 80
PostProcess:
  Topk:
    label_list:
    - 0_degree
    - 180_degree
";
        let config = PaddleInferenceConfig::from_yaml_str(yml).unwrap();
        assert_eq!(config.cls_resize_size, Some([160, 80]));
        assert_eq!(
            config.label_list,
            Some(vec!["0_degree".into(), "180_degree".into()])
        );
    }

    #[test]
    fn parses_nested_sequences_and_anchors() {
        let root = parse_yaml(DET_YML).unwrap();
        let shapes = root
            .get("Hpi")
            .and_then(|h| h.get("backend_configs"))
            .and_then(|b| b.get("paddle_infer"))
            .and_then(|p| p.get("trt_dynamic_shapes"))
            .and_then(|t| t.get("x"))
            .and_then(Yaml::as_seq)
            .unwrap();
        assert_eq!(shapes.len(), 2);
        assert_eq!(
            shapes[1],
            Yaml::Seq(vec![
                Yaml::Scalar("1".into()),
                Yaml::Scalar("3".into()),
                Yaml::Scalar("736".into()),
                Yaml::Scalar("736".into()),
            ])
        );
    }

    #[test]
    fn parses_recognition_dictionary_with_quoting() {
        let yml = "PreProcess:\n  transform_ops:\n  - RecResizeImg:\n      image_shape:\n      - 3\n      - 48\n      - 320\nPostProcess:\n  name: CTCLabelDecode\n  character_dict:\n  - '!'\n  - ''''\n  - '\"'\n  - \\\n  - ':'\n  - a\n  - \"\\u3000\"\n  - '- '\n  - 'a: b'\n  - 'null'\n  - 日\n";
        let config = PaddleInferenceConfig::from_yaml_str(yml).unwrap();
        assert_eq!(config.rec_image_shape, Some([3, 48, 320]));
        assert_eq!(
            config.character_dict.unwrap(),
            vec!["!", "'", "\"", "\\", ":", "a", "\u{3000}", "- ", "a: b", "null", "日"]
        );
    }

    #[test]
    fn keeps_unicode_whitespace_characters() {
        // U+3000 (ideographic space) is not YAML whitespace and must survive.
        let yml = "PostProcess:\n  character_dict:\n  - \u{3000}\n  - x\n";
        let config = PaddleInferenceConfig::from_yaml_str(yml).unwrap();
        assert_eq!(config.character_dict.unwrap(), vec!["\u{3000}", "x"]);
    }

    #[test]
    fn rejects_flow_collections() {
        let err = PaddleInferenceConfig::from_yaml_str("PostProcess:\n  character_dict: [a, b]\n")
            .unwrap_err();
        assert!(matches!(err, PaddleConfigError::Syntax { .. }));
    }

    #[test]
    fn parses_fractional_expressions() {
        assert_eq!(parse_number("1./255."), Some(1.0 / 255.0));
        assert_eq!(parse_number("0.5"), Some(0.5));
        assert_eq!(parse_number("abc"), None);
    }
}
